name = input('Enter your name:')
surname = input('Enter your surname:')
age = int(input('Enter your age:'))
# print(age, type(age))
print(f'Hello, your name is {name}, your surname is {surname}, your age is {age}')
